import { v4 as uuidv4 } from 'uuid'

const items = [
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
        name: "White T-shirt with black sleeves",
        description: 'Everyday T, only for the best',
        price: '12.99',
        type: 't-shirt',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
        name: "Blue old-school backpack",
        description: " Can fit up to 15 laptops inside",
        price: '121.99',
        type: 'bag',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
        name: "Blue slim-fit sweater",
        description: 'For when you are cool',
        price: '7.99',
        type: 'cap',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
        name: "Men's cotton jacket",
        description: 'The slave product',
        price: '42.99',
        type: 'jacket',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
        name: "Cool sweater",
        description: "For when you're cool",
        price: '121.99',
        type: 'sweater',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
        name: "Red Cap",
        description: 'Yankee',
        price: '7.99',
        type: 'cap',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
        name: "White T-shirt",
        description: 'Everyday T, only for the best',
        price: '12.99',
        type: 't-shirt',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
        name: "Cool sweater",
        description: "For when you're cool",
        price: '121.99',
        type: 'sweater',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
        name: "Red Cap",
        description: 'Yankee',
        price: '7.99',
        type: 'cap',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
        name: "White T-shirt",
        description: 'Everyday T, only for the best',
        price: '12.99',
        type: 't-shirt',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
        name: "Cool sweater",
        description: "For when you're cool",
        price: '121.99',
        type: 'sweater',
        cartCount: 0,
    },
    {
        id: uuidv4(),
        photo: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
        name: "Red Cap",
        description: 'Yankee',
        price: '7.99',
        type: 'cap',
        cartCount: 0,
    },
]

export {items}